SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[CalculatedData].[Alias]') AND type in (N'U'))
BEGIN
CREATE TABLE [CalculatedData].[Alias](
	[AliasID] [int] IDENTITY(1,1) NOT NULL,
	[AliasName] [varchar](255) NULL,
	[fkPreviousAliasID] [int] NULL,
	[fkNextAliasID] [int] NULL,
 CONSTRAINT [PK_Alias] PRIMARY KEY CLUSTERED 
(
	[AliasID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [CALCULATED_DATA]
) ON [CALCULATED_DATA]
END
GO
SET ANSI_PADDING OFF
GO
