SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SiteData].[WeaponGroup]') AND type in (N'U'))
BEGIN
CREATE TABLE [SiteData].[WeaponGroup](
	[WeaponGroupID] [int] IDENTITY(1,1) NOT NULL,
	[WeaponGroupName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_WeaponGroup] PRIMARY KEY CLUSTERED 
(
	[WeaponGroupID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [SITE_DATA]
) ON [SITE_DATA]
END
GO
SET ANSI_PADDING OFF
GO
