/****** Object:  Login [T30\SQLServer2005MSFTEUser$T30$TOM_SQL_SVR]    Script Date: 04/19/2009 22:46:53 ******/
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'T30\SQLServer2005MSFTEUser$T30$TOM_SQL_SVR')
CREATE LOGIN [T30\SQLServer2005MSFTEUser$T30$TOM_SQL_SVR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'T30\SQLServer2005MSFTEUser$T30$TOM_SQL_SVR')
CREATE LOGIN [T30\SQLServer2005MSFTEUser$T30$TOM_SQL_SVR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'T30\SQLServer2005MSFTEUser$T30$TOM_SQL_SVR')
CREATE LOGIN [T30\SQLServer2005MSFTEUser$T30$TOM_SQL_SVR] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
