/****** Object:  Login [T30\ASPNET]    Script Date: 04/19/2009 22:46:53 ******/
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'T30\ASPNET')
CREATE LOGIN [T30\ASPNET] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'T30\ASPNET')
CREATE LOGIN [T30\ASPNET] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'T30\ASPNET')
CREATE LOGIN [T30\ASPNET] FROM WINDOWS WITH DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english]
GO
